#! /bin/sh
":"; exec emacs --no-site-file --script "$0" -- "$0" "$@" # -*-emacs-lisp-*-
; vim: noai:ts=4:sw=4:syntax=lisp

(setq arg0 (file-truename (car (cdr argv))))
(setq args (cdr (cdr argv)))
(setq argv nil)

(setq args (mapcar (lambda (arg)
             (when (string-match "^--\\([^=]*\\)\\(?:=\\(.*\\)\\)?" arg)
               (let ((opt (match-string 1 arg))
                 (val (match-string 2 arg)))
                 (if val
                 (list opt val)
                   (list opt)))))
            args))
(mapc (lambda (arg) (set (intern (car arg)) (if (cdr arg) (cdr arg) t))) args)

(setq basedir (concat (file-name-directory arg0) "macs-verilog-mode"))
(setq load-path (cons basedir load-path))

(defun insert-standard-input ()
  "insert contents from standard input"
  (condition-case nil
      (let (line) 
        (while (setq line (read-from-minibuffer ""))
          (insert line "\n")))
    (error nil)))

(insert-standard-input)
(goto-char (point-min))

(load-library "verilog-mode")
(verilog-mode)
(verilog-indent-buffer)

(princ (buffer-string))
